module.exports = {
  RAIZ: '/',
  API: '/api',
  AUTENTICACION: {
    BASE: '/autenticacion',
    INICIO_SESION: '/iniciar-sesion',
    REGISTRO: '/registro',
    CERRAR_SESION: '/cerrar-sesion',
    USUARIO_AUTENTICADO: '/autenticar',
    ACTIVAR_2FA: '/activar-2fa',
    VERIFICAR_2FA: '/verificar-2fa',
  },
  USUARIOS: {
    BASE: '/usuarios',
    CONSULTAR_LISTA_USUARIOS: '/consultar-lista-usuarios',
    CREAR: '/crear',
    ELIMINAR_USUARIOS: '/eliminar-usuarios',
    LEER: '/consultar-usuario',
  },
  CATEGORIAS: {
    BASE: '/categorias',
    CONSULTAR_LISTA_CATEGORIAS: '/consultar-lista-categorias',
    CREAR_CATEGORIA: '/crear-categoria',
    ELIMINAR_CATEGORIA: '/eliminar',
    CONSULTAR_LISTA_USUARIOS: '/consultar-lista-usuarios',
    CREAR: '/crear',
    ELIMINAR_USUARIOS: '/eliminar-usuarios',
    LEER: '/leer',
  },
  EVENTOS: {
    BASE: '/eventos',
    CREAR: '/crear',
    ELIMINAR: '/eliminar',
    EDITAR: '/editar',
    CONSULTAR_LISTA_EVENTOS: '/consultar-lista-eventos',
    CONSULTAR_EVENTO: '/consultar-evento',
  },
  PRODUCTOS: {
    BASE: '/productos',
    CONSULTAR_LISTA: '/consultar-lista',
    CREAR: '/crear',
    ELIMINAR_PRODUCTO: '/eliminar',
    IMPORTAR: '/importar',
    LEER: '/leer-producto'
  },
  PROVEEDORES: {
    BASE: '/proveedores',
    CONSULTAR_LISTA: '/consultar-lista',
    CREAR: '/crear',
  },
  SETS_PRODUCTOS: {
    BASE: '/sets-productos',
    CONSULTAR_LISTA: '/consultar-lista',
    CREAR: '/crear',
    SUBIR_IMAGEN: '/subir-imagen',
    ELIMINAR_SET_PRODUCTOS: '/eliminar',
  },
  CLIENTES: {
    BASE: '/clientes',
    CONSULTAR_SISTEMA: '/consultar-sistema',
    CONSULTAR_LISTA: '/consultar-lista',
    ELIMINAR_CLIENTE: '/eliminar',
    CREAR_CLIENTE: '/crear-cliente',
    LEER: '/consultar-cliente',
    ACTUALIZAR: `/actualizar-cliente`,
  },
  EMPLEADOS: {
    BASE: '/empleados',
    CONSULTAR_LISTA: '/consultar-lista',
    CONSULTAR_GRUPO: '/consultar-grupo',
    ELIMINAR_GRUPO: '/eliminar-grupo',
    ELIMINAR_EMPLEADO: '/eliminar',
    IMPORTAR_EMPLEADOS: '/importar-empleados',
    LEER_GRUPO: '/leer-grupo',
    CREAR_GRUPO: '/crear-grupo',
    ACTUALIZAR: '/actualizar',
  },
  CUOTAS: {
    BASE: '/cuotas',
    AGREGAR: '/crear-cuota',
    OPCIONES: '/obtener-opciones',
    CONSULTAR_LISTA: '/consultar-lista',
    ELIMINAR_SET_CUOTAS: '/eliminar-set-cuotas',
  },
  ROLES: {
    BASE: '/roles',
    CONSULTAR_LISTA: '/consultar-lista',
    CREAR_ROL: '/crear-rol',
    OBTENER_OPCIONES: '/obtener-opciones',
    CONFIRMAR_CREACION: '/confirmar-creacion',
    ELIMINAR_ROL: '/eliminar',
    LEER_ROL: '/leer',
  },
  PEDIDOS: {
    BASE: '/pedidos',
    CONSULTAR_LISTA: '/consultar-lista',
    ELIMINAR_PEDIDO: '/eliminar',
  },
  PAGOS: {
    BASE: '/pagos',
    CONSULTAR_LISTA: '/consultar-lista',
    ACTUALIZAR: '/actualizar',
  },
  API_DOCS: '/api-docs',
};